from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


class SearchStatus(str, Enum):
    PENDING = "pending"
    DECOMPOSING = "decomposing"
    SEARCHING = "searching"
    ENRICHING = "enriching"
    EVALUATING = "evaluating"
    COMPLETED = "completed"
    FAILED = "failed"


class SearchStrategy(BaseModel):
    """A single search sub-query generated by the decomposer."""

    description: str
    google_dork: str | None = None
    apollo_params: dict | None = None
    apify_params: dict | None = None
    proxycurl_params: dict | None = None


class SearchCriteria(BaseModel):
    """Structured search criteria extracted from natural language."""

    job_titles: list[str] = Field(default_factory=list)
    locations: list[str] = Field(default_factory=list)
    industries: list[str] = Field(default_factory=list)
    keywords: list[str] = Field(default_factory=list)
    company_attributes: dict = Field(default_factory=dict)
    experience_requirements: list[str] = Field(default_factory=list)
    education_requirements: list[str] = Field(default_factory=list)
    seniority_levels: list[str] = Field(default_factory=list)
    boolean_logic: str = ""
    search_strategies: list[SearchStrategy] = Field(default_factory=list)
    semantic_intent: str = ""


class SearchSession(BaseModel):
    """Tracks a search from query to results."""

    id: str = Field(default_factory=lambda: uuid4().hex[:12])
    natural_query: str
    criteria: SearchCriteria | None = None
    status: SearchStatus = SearchStatus.PENDING
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    result_count: int = 0
    provider_stats: dict[str, int] = Field(default_factory=dict)
    error_message: str | None = None
